### ISSUE TITLE
2팀 코드리뷰

### ISSUE THREAD

**Issue by yoonminsang** [woowa-techcamp-2021/store-3#103]
https://github.com/woowa-techcamp-2021/store-3/pull/66#issuecomment-902446608

**Comment by negu63** [comment]
https://github.com/woowa-techcamp-2021/store-3/commit/7b1646de437f80886fdf1d161706278edc506270#commitcomment-55174910

https://github.com/woowa-techcamp-2021/store-3/pull/57#issuecomment-902446805

잘 보고 갑니다! 화이팅~
