### ISSUE TITLE
[BUG] 아이템 개수소수 입력

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/store-3#225]
![스크린샷 2021-08-27 오후 2 09 57](https://user-images.githubusercontent.com/35324795/131075058-f8757bcd-963b-471f-a57a-bffa72cd844f.png)

아이템 선택시 소수가 입력가능합니다..

**Comment by SecretJuJu** [comment]
프론트/백 모두 validation 을 하도록 하겠습니다 :)
