### ISSUE TITLE
상품 찜 했을때 UI에 표시되지 않음

### ISSUE THREAD

**Issue by Choi-Jinwoo** [woowa-techcamp-2021/store-3#237]
OS: Mac
Browser: Chrome

상품을 찜했을때 상품 찜한 리스트 페이지로 이동한 후 뒤로가면 찜 UI에 활성화가 안되어 있습니다!

![image](https://user-images.githubusercontent.com/49791336/131077724-be2d85e2-ca5d-483f-826c-63520b892c31.png)

**Comment by SecretJuJu** [comment]
사실 구현이 안되어 있었죠 ㅋㅋㅋㅋ
