### ISSUE TITLE
찜리스트 삭제하기 버튼 클릭 시 create wish api 실행하는 문제 수정 

### ISSUE THREAD

**Issue by hwookim** [woowa-techcamp-2021/store-3#255]
## :hammer: 이슈 설명

```typescript
  const onDeleteWishes = async (itemIds: number[]) => {
    await Promise.all(itemIds.map((id) => createWishMutate(id)));
    refetch();
  };
```

## 📑 체크리스트
> 수행해야 할 체크리스트

- [ ] deletWish 구현 후 삭제 진행

## 예상 소요 시간
> 이슈를 해결하기 위해 사용된 시간

- 30분

## 🚧 주의 사항
> 기능을 구현할 때 유의깊게 살펴볼 사항

**Comment by chaeeun037** [comment]
해당 이슈는 기존의 `postWishMutation`이 toggle형식으로 동작하는데, `createWishMutation`로 이름이 변경되면서 차질이 있었네요!
말씀 나눈대로 `toggleWishMutation`등의 이름으로 바꾸고, 기능적인 수정 사항은 더이상 없을것 같습니다 :)
