### ISSUE TITLE
[제보필요] 로그아웃이 두번 눌러야 되는 버그1?!?

### ISSUE THREAD

**Issue by chaeeun037** [woowa-techcamp-2021/store-3#266]
## :hammer: 이슈 설명

가끔 로그아웃이 두번 눌러야 되는 버그를 마주쳤는데 버그 재현이 불가해서 보류하겠습니다..
제보해주세요!

## 📑 체크리스트
> 수행해야 할 체크리스트

- [ ] 체크 사항 1

## 예상 소요 시간
> 이슈를 해결하기 위해 사용된 시간

- 0시간

## 🚧 주의 사항
> 기능을 구현할 때 유의깊게 살펴볼 사항

- 주의 사항 1

<선택> 이해를 돕기 위한 스크린샷을 첨부해주세요.

**Comment by hwookim** [comment]
저는 한번에 잘 되는데 어떤 상황일까요??

**Comment by chaeeun037** [comment]
아마 개발모드에서 서버 재시작되면서 생기는 버그같기도 합니다. 
로그아웃 로직 처리 타이밍 이슈인거 같기도 하고요. 아직 원인 파악은 안되고있습니다 ㅜㅜ
프로덕션에서는 경험해보지 못하기도 해서...

**Comment by chaeeun037** [comment]
버그는 없었습니다 . ㅎㅎ
