### ISSUE TITLE
Auth Middleware 수정

### ISSUE THREAD

**Issue by chaeeun037** [woowa-techcamp-2021/store-3#36]
## :hammer: 이슈 설명

Auth Middleware 수정

## 📑 체크리스트
> 수행해야 할 체크리스트

- [ ] jwt 대상이 userId인지
- [ ] 변경 사항에 대해 테스트를 진행했는지

## 예상 소요 시간
> 이슈를 해결하기 위해 사용된 시간

- 1시간

## 🚧 주의 사항
> 기능을 구현할 때 유의깊게 살펴볼 사항

**Comment by SecretJuJu** [comment]
혹시 authMiddleware에서 사용하고있는 IAuthRequest 라는 interface 의 user를 optional 옵션을 빼주실 수 있나요? 
이미 req.user 에 user를 채워주는것은 verifyJWT 에서 에러가 없어야 채워지는 것 같아서 optional이 아니여도 될 것 같아요!

**Comment by SecretJuJu** [comment]
아 그리고 현재 default_address가 토큰 안에 있어서 이걸 사용하면 address api 중 updateAddress 기능에 유저의 default_address 조회하지 않아도 될 것 같은데 이걸 토큰안에 남겨두는것이 좋을까요 아니면 토큰에서 지우고 따로 처리하는것이 좋을까요?
